[package]
name = "kindle_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssh = { version = "0.11.3", features = ["native-mux"] }
thiserror = "2.0.3"
tokio = "1.41.1"
